// <auto-generated />
using System;
using LiveStream.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LiveStream.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906100927_Phase7ScaleSecurityGovernance")]
    partial class Phase7ScaleSecurityGovernance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LiveStream.Domain.Ai.AiJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("kind");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<string>("ModelId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_id");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset?>("SourceRangeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_range_end");

                    b.Property<DateTimeOffset?>("SourceRangeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_range_start");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_jobs");

                    b.HasIndex("LiveSessionId", "RequestedAt")
                        .HasDatabaseName("ix_ai_jobs_live_session_id_requested_at");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_ai_jobs_status_next_attempt_at");

                    b.ToTable("ai_jobs", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Distribution.DestinationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("StreamDestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("stream_destination_id");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_destination_events");

                    b.HasIndex("StreamDestinationId", "CreatedAt")
                        .HasDatabaseName("ix_destination_events_destination_created");

                    b.ToTable("destination_events", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Distribution.ProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenCipher")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("access_token_cipher");

                    b.Property<DateTimeOffset?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_account_id");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<Guid>("LinkedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_by_user_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("RefreshTokenCipher")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("refresh_token_cipher");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_provider_accounts");

                    b.HasIndex("WorkspaceId", "Provider", "ExternalAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_accounts_workspace_provider_external");

                    b.ToTable("provider_accounts", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Distribution.StreamDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_sent");

                    b.Property<long>("BytesSentBaseline")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_sent_baseline");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("credential_mode");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ExternalBroadcastId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_broadcast_id");

                    b.Property<string>("IngestUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ingest_url");

                    b.Property<DateTimeOffset?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connected_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error_message");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<Guid?>("ProviderAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_account_id");

                    b.Property<string>("ResolvedIngestUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolved_ingest_url");

                    b.Property<string>("ResolvedStreamKeyCipher")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("resolved_stream_key_cipher");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset>("StateEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_entered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.Property<string>("StreamKeyCipher")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("stream_key_cipher");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("WatchUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("watch_url");

                    b.HasKey("Id")
                        .HasName("pk_stream_destinations");

                    b.HasIndex("ProviderAccountId")
                        .HasDatabaseName("ix_stream_destinations_provider_account_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_stream_destinations_status");

                    b.HasIndex("LiveSessionId", "CreatedAt")
                        .HasDatabaseName("ix_stream_destinations_session_created");

                    b.ToTable("stream_destinations", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Governance.RuntimeLease", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("FencingToken")
                        .HasColumnType("bigint")
                        .HasColumnName("fencing_token");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Name")
                        .HasName("pk_runtime_leases");

                    b.ToTable("runtime_leases", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Governance.WorkspaceLimits", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("MaxConcurrentSessionsOverride")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_sessions_override");

                    b.Property<int?>("MaxDestinationsPerSessionOverride")
                        .HasColumnType("integer")
                        .HasColumnName("max_destinations_per_session_override");

                    b.Property<int?>("MaxSourcesPerSessionOverride")
                        .HasColumnType("integer")
                        .HasColumnName("max_sources_per_session_override");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("plan");

                    b.Property<int?>("RecordingRetentionDaysOverride")
                        .HasColumnType("integer")
                        .HasColumnName("recording_retention_days_override");

                    b.Property<string>("ResidencyRegion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("residency_region");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WorkspaceId")
                        .HasName("pk_workspace_limits");

                    b.ToTable("workspace_limits", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_expires");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_identities_user_id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_user_identities_issuer_subject");

                    b.ToTable("user_identities", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_workspaces_owner_user_id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_members_workspace_user");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.WorkspaceSsoConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecretCiphertext")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("client_secret_ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultRole")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("default_role");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<bool>("JitProvisioning")
                        .HasColumnType("boolean")
                        .HasColumnName("jit_provisioning");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("protocol");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_sso_connections");

                    b.HasIndex("WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_sso_connections_workspace_id");

                    b.ToTable("workspace_sso_connections", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.WorkspaceSsoDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_workspace_sso_domains");

                    b.HasIndex("ConnectionId")
                        .HasDatabaseName("ix_workspace_sso_domains_connection_id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_sso_domains_domain");

                    b.ToTable("workspace_sso_domains", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Media.IngestCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("FirstUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_used_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_to_user_id");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<string>("MediaPathName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("media_path_name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_ingest_credentials");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_ingest_credentials_token_hash");

                    b.HasIndex("LiveSessionId", "ExpiresAt")
                        .HasDatabaseName("ix_ingest_credentials_session_expires");

                    b.ToTable("ingest_credentials", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Recordings.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<string>("MediaFormat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("media_format");

                    b.Property<int>("SegmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("segment_count");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recordings");

                    b.HasIndex("LiveSessionId", "Status")
                        .HasDatabaseName("ix_recordings_session_status");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_recordings_status_expires_at");

                    b.ToTable("recordings", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Sessions.LiveSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error_message");

                    b.Property<string>("MediaPathName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("media_path_name");

                    b.Property<bool>("RecordingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("recording_enabled");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset>("StateEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_entered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("visibility");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_live_sessions");

                    b.HasIndex("MediaPathName")
                        .IsUnique()
                        .HasDatabaseName("ix_live_sessions_media_path");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_live_sessions_status");

                    b.HasIndex("WorkspaceId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_live_sessions_workspace_status_created");

                    b.ToTable("live_sessions", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Sessions.LiveSessionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_live_session_events");

                    b.HasIndex("LiveSessionId", "CreatedAt")
                        .HasDatabaseName("ix_live_session_events_session_created");

                    b.ToTable("live_session_events", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Sessions.LiveSessionHealth", b =>
                {
                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("integer")
                        .HasColumnName("bitrate_kbps");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_received");

                    b.Property<bool>("IngestConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("ingest_connected");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset?>("LastIngestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ingest_at");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int>("ReconnectCount")
                        .HasColumnType("integer")
                        .HasColumnName("reconnect_count");

                    b.Property<DateTimeOffset?>("RecoveryStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovery_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int?>("VideoFps")
                        .HasColumnType("integer")
                        .HasColumnName("video_fps");

                    b.Property<int>("ViewerCount")
                        .HasColumnType("integer")
                        .HasColumnName("viewer_count");

                    b.HasKey("LiveSessionId")
                        .HasName("pk_live_session_health");

                    b.ToTable("live_session_health", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Sources.SessionSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("integer")
                        .HasColumnName("bitrate_kbps");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_received");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeviceTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_token_expires_at");

                    b.Property<string>("DeviceTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_token_hash");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IngestConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("ingest_connected");

                    b.Property<bool>("IsProgram")
                        .HasColumnType("boolean")
                        .HasColumnName("is_program");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<string>("MediaPathName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("media_path_name");

                    b.Property<DateTimeOffset?>("PairedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paired_at");

                    b.Property<DateTimeOffset?>("PairingCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pairing_code_expires_at");

                    b.Property<string>("PairingCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pairing_code_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("StateEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_entered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_session_sources");

                    b.HasIndex("DeviceTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_session_sources_device_token_hash");

                    b.HasIndex("MediaPathName")
                        .HasDatabaseName("ix_session_sources_media_path");

                    b.HasIndex("PairingCodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_session_sources_pairing_code_hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_session_sources_status");

                    b.HasIndex("LiveSessionId", "CreatedAt")
                        .HasDatabaseName("ix_session_sources_session_created");

                    b.ToTable("session_sources", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Sources.SourceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("SessionSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_source_id");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_source_events");

                    b.HasIndex("SessionSourceId", "CreatedAt")
                        .HasDatabaseName("ix_source_events_source_created");

                    b.ToTable("source_events", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Studio.SessionBranding", b =>
                {
                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("accent_color");

                    b.Property<string>("LogoDataUri")
                        .HasMaxLength(262144)
                        .HasColumnType("character varying(262144)")
                        .HasColumnName("logo_data_uri");

                    b.Property<int>("LogoOpacityPercent")
                        .HasColumnType("integer")
                        .HasColumnName("logo_opacity_percent");

                    b.Property<string>("LogoPosition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("logo_position");

                    b.Property<bool>("ShowLogo")
                        .HasColumnType("boolean")
                        .HasColumnName("show_logo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LiveSessionId")
                        .HasName("pk_session_branding");

                    b.ToTable("session_branding", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Studio.SessionScene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("layout");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<string>("LowerThirdSubtitle")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lower_third_subtitle");

                    b.Property<string>("LowerThirdTitle")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lower_third_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("PrimarySourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_source_id");

                    b.Property<Guid?>("SecondarySourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("secondary_source_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_session_scenes");

                    b.HasIndex("LiveSessionId", "Position")
                        .HasDatabaseName("ix_session_scenes_live_session_id_position");

                    b.ToTable("session_scenes", (string)null);
                });

            modelBuilder.Entity("LiveStream.Domain.Ai.AiJob", b =>
                {
                    b.HasOne("LiveStream.Domain.Sessions.LiveSession", "LiveSession")
                        .WithMany()
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_jobs_live_sessions_live_session_id");

                    b.Navigation("LiveSession");
                });

            modelBuilder.Entity("LiveStream.Domain.Distribution.DestinationEvent", b =>
                {
                    b.HasOne("LiveStream.Domain.Distribution.StreamDestination", "StreamDestination")
                        .WithMany("Events")
                        .HasForeignKey("StreamDestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_destination_events_stream_destinations_stream_destination_id");

                    b.Navigation("StreamDestination");
                });

            modelBuilder.Entity("LiveStream.Domain.Distribution.StreamDestination", b =>
                {
                    b.HasOne("LiveStream.Domain.Sessions.LiveSession", "LiveSession")
                        .WithMany()
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stream_destinations_live_sessions_live_session_id");

                    b.HasOne("LiveStream.Domain.Distribution.ProviderAccount", "ProviderAccount")
                        .WithMany("Destinations")
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stream_destinations_provider_accounts_provider_account_id");

                    b.Navigation("LiveSession");

                    b.Navigation("ProviderAccount");
                });

            modelBuilder.Entity("LiveStream.Domain.Governance.WorkspaceLimits", b =>
                {
                    b.HasOne("LiveStream.Domain.Identity.Workspace", "Workspace")
                        .WithOne()
                        .HasForeignKey("LiveStream.Domain.Governance.WorkspaceLimits", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_limits_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("LiveStream.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.UserIdentity", b =>
                {
                    b.HasOne("LiveStream.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_identities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.WorkspaceMember", b =>
                {
                    b.HasOne("LiveStream.Domain.Identity.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_users_user_id");

                    b.HasOne("LiveStream.Domain.Identity.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.WorkspaceSsoConnection", b =>
                {
                    b.HasOne("LiveStream.Domain.Identity.Workspace", "Workspace")
                        .WithOne()
                        .HasForeignKey("LiveStream.Domain.Identity.WorkspaceSsoConnection", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_sso_connections_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.WorkspaceSsoDomain", b =>
                {
                    b.HasOne("LiveStream.Domain.Identity.WorkspaceSsoConnection", "Connection")
                        .WithMany("Domains")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_sso_domains_workspace_sso_connections_connection_~");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("LiveStream.Domain.Media.IngestCredential", b =>
                {
                    b.HasOne("LiveStream.Domain.Sessions.LiveSession", "LiveSession")
                        .WithMany("IngestCredentials")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingest_credentials_live_sessions_live_session_id");

                    b.Navigation("LiveSession");
                });

            modelBuilder.Entity("LiveStream.Domain.Recordings.Recording", b =>
                {
                    b.HasOne("LiveStream.Domain.Sessions.LiveSession", "LiveSession")
                        .WithMany("Recordings")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recordings_live_sessions_live_session_id");

                    b.Navigation("LiveSession");
                });

            modelBuilder.Entity("LiveStream.Domain.Sessions.LiveSessionEvent", b =>
                {
                    b.HasOne("LiveStream.Domain.Sessions.LiveSession", "LiveSession")
                        .WithMany("Events")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_live_session_events_live_sessions_live_session_id");

                    b.Navigation("LiveSession");
                });

            modelBuilder.Entity("LiveStream.Domain.Sessions.LiveSessionHealth", b =>
                {
                    b.HasOne("LiveStream.Domain.Sessions.LiveSession", "LiveSession")
                        .WithOne("Health")
                        .HasForeignKey("LiveStream.Domain.Sessions.LiveSessionHealth", "LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_live_session_health_live_sessions_live_session_id");

                    b.Navigation("LiveSession");
                });

            modelBuilder.Entity("LiveStream.Domain.Sources.SessionSource", b =>
                {
                    b.HasOne("LiveStream.Domain.Sessions.LiveSession", "LiveSession")
                        .WithMany("Sources")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_sources_live_sessions_live_session_id");

                    b.Navigation("LiveSession");
                });

            modelBuilder.Entity("LiveStream.Domain.Sources.SourceEvent", b =>
                {
                    b.HasOne("LiveStream.Domain.Sources.SessionSource", "SessionSource")
                        .WithMany("Events")
                        .HasForeignKey("SessionSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_events_session_sources_session_source_id");

                    b.Navigation("SessionSource");
                });

            modelBuilder.Entity("LiveStream.Domain.Studio.SessionBranding", b =>
                {
                    b.HasOne("LiveStream.Domain.Sessions.LiveSession", "LiveSession")
                        .WithOne("Branding")
                        .HasForeignKey("LiveStream.Domain.Studio.SessionBranding", "LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_branding_live_sessions_live_session_id");

                    b.Navigation("LiveSession");
                });

            modelBuilder.Entity("LiveStream.Domain.Studio.SessionScene", b =>
                {
                    b.HasOne("LiveStream.Domain.Sessions.LiveSession", "LiveSession")
                        .WithMany("Scenes")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_scenes_live_sessions_live_session_id");

                    b.Navigation("LiveSession");
                });

            modelBuilder.Entity("LiveStream.Domain.Distribution.ProviderAccount", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("LiveStream.Domain.Distribution.StreamDestination", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.Workspace", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("LiveStream.Domain.Identity.WorkspaceSsoConnection", b =>
                {
                    b.Navigation("Domains");
                });

            modelBuilder.Entity("LiveStream.Domain.Sessions.LiveSession", b =>
                {
                    b.Navigation("Branding")
                        .IsRequired();

                    b.Navigation("Events");

                    b.Navigation("Health")
                        .IsRequired();

                    b.Navigation("IngestCredentials");

                    b.Navigation("Recordings");

                    b.Navigation("Scenes");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("LiveStream.Domain.Sources.SessionSource", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
