<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>LiveStream.Api</RootNamespace>
    <UserSecretsId>livestream-api-phase1</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LiveStream.Infrastructure\LiveStream.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LiveStream.IntegrationTests" />
  </ItemGroup>
</Project>
